function environments = getEnvironmentPresets_stage9()
% getEnvironmentPresets_stage9
% Returns simplified launch-environment sensitivity presets.
%
% These are engineering trade-study perturbations only. They are not live
% weather, atmospheric soundings, wind profiles, or forecasts.

environments(1) = makeEnvironment( ...
    'Standard atmosphere / baseline', 0, 1.00, 1.00, 0, [0; 0; 0], ...
    'Baseline Stage 4 atmosphere and no additional wind.');

environments(2) = makeEnvironment( ...
    'Hot day', 15, 1.00, 1.00, 0, [0; 0; 0], ...
    'Uniform +15 K temperature offset; density follows pressure/(R*T).');

environments(3) = makeEnvironment( ...
    'Cold day', -15, 1.00, 1.00, 0, [0; 0; 0], ...
    'Uniform -15 K temperature offset; density follows pressure/(R*T).');

environments(4) = makeEnvironment( ...
    'High-altitude launch site', 0, 1.00, 1.00, 1500, [0; 0; 0], ...
    'Launch altitude raised by 1500 m.');

environments(5) = makeEnvironment( ...
    'Dense air / high-pressure case', 0, 1.10, 1.05, 0, [0; 0; 0], ...
    'Density multiplier 1.10 and pressure multiplier 1.05.');

environments(6) = makeEnvironment( ...
    'Thin air / low-pressure case', 0, 0.90, 0.95, 0, [0; 0; 0], ...
    'Density multiplier 0.90 and pressure multiplier 0.95.');

environments(7) = makeEnvironment( ...
    'Headwind case', 0, 1.00, 1.00, 0, [-50; 0; 0], ...
    'Constant 50 m/s launch-site headwind against eastward launch.');

environments(8) = makeEnvironment( ...
    'Tailwind case', 0, 1.00, 1.00, 0, [50; 0; 0], ...
    'Constant 50 m/s launch-site tailwind with eastward launch.');

environments(9) = makeEnvironment( ...
    'Crosswind case', 0, 1.00, 1.00, 0, [0; 50; 0], ...
    'Constant 50 m/s northward launch-site crosswind.');

end

function environment = makeEnvironment(name, tempOffset_K, densityMultiplier, ...
        pressureMultiplier, launchAltitudeOffset_m, windENU_mps, notes)
environment.name = name;
environment.temperatureOffset_K = tempOffset_K;
environment.temperatureMultiplier = 1.0;
environment.densityMultiplier = densityMultiplier;
environment.pressureMultiplier = pressureMultiplier;
environment.launchAltitudeOffset_m = launchAltitudeOffset_m;
environment.windENU_mps = windENU_mps;
environment.windSpeed_mps = norm(windENU_mps);
environment.notes = notes;
end
