function [vehicle, stage11Config] = applyDesignVector(config, design)
% applyDesignVector
% Applies a Stage 13 design vector to a Stage 11 vehicle and config.

vehicle = config.baseVehicle;
vehicle.bodyType = char(design.bodyType);
vehicle.noseType = char(design.noseType);
vehicle.mass = design.mass_kg;
vehicle.length = design.length_m;
vehicle.diameter = design.diameter_m;
vehicle.referenceArea = design.referenceArea_m2;
vehicle.area = vehicle.referenceArea;
vehicle.finenessRatio = design.finenessRatio;
vehicle.fineness = design.finenessRatio;
vehicle.noseRadius_m = design.noseRadius_m;
vehicle.cgLocation_m = design.cgLocation_m;
vehicle.cpLocation_m = design.cpLocation_m;
vehicle.staticMargin = design.staticMargin;
vehicle.V0 = design.initialSpeed_mps;
vehicle.launchAngle = design.launchAngle_deg;
vehicle.Cd_scale = design.CdMultiplier;
vehicle.CL_scale = design.CLalphaMultiplier;
vehicle.dragUncertaintyFactor = design.dragUncertaintyFactor;
vehicle.liftUncertaintyFactor = design.liftUncertaintyFactor;
vehicle.hasFins = contains(lower(char(design.bodyType)), 'finned');
vehicle = buildVehicleFromGeometry_stage11(vehicle, vehicle.bodyType);

stage11Config = buildStage11Config(vehicle, config.constants, struct( ...
    'mode', 1, ...
    'showPlots', false, ...
    'exportResults', false, ...
    'generateReport', false, ...
    'verbose', false, ...
    'interactive', false, ...
    'figureVisible', 'off', ...
    'dofMode', config.stage11.dofMode, ...
    'tFinal_s', config.stage11.tFinal_s, ...
    'maxStep_s', config.stage11.maxStep_s, ...
    'launchAngle_deg', design.launchAngle_deg, ...
    'launchYaw_deg', design.initialYaw_deg, ...
    'launchSpeed_mps', design.initialSpeed_mps, ...
    'initialAltitude_m', design.initialAltitude_m, ...
    'outputRoot', fullfile(config.outputRoot, 'Stage11CaseScratch')));
stage11Config.environment.windSpeed_mps = design.windSpeed_mps;
stage11Config.environment.windDirection_deg = design.windDirection_deg;
stage11Config.environment.densityMultiplier = design.densityMultiplier;
stage11Config.environment.temperatureMultiplier = design.temperatureMultiplier;
end
