function presets = getVehiclePresets_stage6(baseVehicle)
% getVehiclePresets_stage6
% Returns approximate vehicle configurations for engineering trade studies.
%
% These presets are not CFD-accurate. They are simple body-configuration
% inputs for comparing trends with the existing Stage 5 / Stage 4 model.

presets(1) = makePreset(baseVehicle, ...
    'Baseline slender body', ...
    'Baseline slender axisymmetric body', ...
    baseVehicle.mass, ...
    baseVehicle.diameter, ...
    baseVehicle.length, ...
    baseVehicle.alpha_deg, ...
    baseVehicle.V0, ...
    1.00);

presets(2) = makePreset(baseVehicle, ...
    'Longer slender body', ...
    'Longer slender axisymmetric body', ...
    5.2, ...
    baseVehicle.diameter, ...
    0.70, ...
    2.0, ...
    baseVehicle.V0, ...
    0.95);

presets(3) = makePreset(baseVehicle, ...
    'Larger-diameter blunter body', ...
    'Larger-diameter approximate blunt body', ...
    5.5, ...
    0.075, ...
    0.45, ...
    2.0, ...
    baseVehicle.V0, ...
    1.20);

presets(4) = makePreset(baseVehicle, ...
    'Higher-mass high-BC body', ...
    'Higher-mass high-ballistic-coefficient body', ...
    8.0, ...
    baseVehicle.diameter, ...
    0.50, ...
    1.5, ...
    baseVehicle.V0, ...
    1.00);

presets(5) = makePreset(baseVehicle, ...
    'Finned lifting-body approximation', ...
    'Approximate finned/lifting body', ...
    5.3, ...
    0.060, ...
    0.50, ...
    4.0, ...
    baseVehicle.V0, ...
    1.05);

end

function vehicle = makePreset(baseVehicle, name, bodyType, mass, diameter, length, alpha_deg, V0, cdScale)
vehicle = baseVehicle;

vehicle.name = name;
vehicle.bodyType = bodyType;
vehicle.shape = bodyType;
vehicle.mass = mass;
vehicle.diameter = diameter;
vehicle.length = length;
vehicle.alpha_deg = alpha_deg;
vehicle.alpha = deg2rad(alpha_deg);
vehicle.V0 = V0;

vehicle.area = pi * vehicle.diameter^2 / 4;
vehicle.referenceArea = vehicle.area;
vehicle.fineness = vehicle.length / vehicle.diameter;
vehicle.finenessRatio = vehicle.fineness;
vehicle.noseRadius_m = vehicle.diameter / 2;

if isfield(vehicle, 'M_table_stage3')
    vehicle.M_table = vehicle.M_table_stage3;
end

if isfield(vehicle, 'Cd0_table_stage3')
    vehicle.Cd_table = max(vehicle.Cd0_table_stage3 .* cdScale, 0.05);
elseif isfield(vehicle, 'Cd_table')
    vehicle.Cd_table = max(vehicle.Cd_table .* cdScale, 0.05);
end
end
